name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
#           - p1-dongle.yaml
#           - p1-dongle-smr2_2.yaml
#           - waterlezer.yaml
          - p1-dongle-pro.yaml
          - p1-dongle-pro-smr2_2.yaml
          - eth-dongle-pro.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1
        with:
          yaml_file: ${{ matrix.file }}
